version: '3.8'

services:
  streamlit-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1